name: buddyGuard_Dev_be_CI_CD

on:
  push:
    branches:
      - dev-be   
  workflow_dispatch:  # 수동으로 트리거 가능하게 설정

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt' # Java 17 사용

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./be/gradlew build -x test  # 테스트 생략하고 빌드

    - name: Transfer files to EC2
      uses: appleboy/scp-action@v0.1.2
      with:
        source: build/libs/your-app.jar  # 빌드 결과물인 JAR 파일 경로
        target: ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/path/to/your/deployment/folder
        key: ${{ secrets.EC2_SSH_KEY }}   # GitHub Secrets에 저장한 SSH Private Key 사용
        port: 22

    - name: SSH into EC2 and restart application
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          pkill -f 'your-app.jar' || true   # 기존 애플리케이션 종료
          nohup java -jar /path/to/your/deployment/folder/your-app.jar &   # 새로운 JAR 파일 실행
