name: buddyGuard Frontend CI/CD using github actions

on:
  push:
    branches:
      - dev-fe
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      # 캐시 지우고 빌드 추가
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Create .env.production file in nginx-vol/fe
        run: |
          sudo mkdir -p /home/ubuntu/nginx-vol/fe
          sudo touch /home/ubuntu/nginx-vol/fe/.env.production
          echo "REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}" >> /home/ubuntu/nginx-vol/fe/.env.production

      - name: Clean and install dependencies
        working-directory: ./fe
        run: |
          rm -rf node_modules package-lock.json
          npm install --force

      - name: Build project
        working-directory: ./fe
        run: pnpm run build

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./fe/dist/*"
          target: "/home/ubuntu/nginx-vol/"
