name: buddyGuard Frontend CI/CD using github actions

# dev-fe 브랜치에 push가 되었을 때 실행
on:
  push:
    branches:
      - dev-fe  # dev-fe 브랜치에서 푸시 이벤트 발생 시 실행
  workflow_dispatch:  # 수동으로 트리거 가능하게 설정

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # 현재 작업 디렉토리 출력 (디버깅용)
      - name: Print working directory for debugging
        run: pwd  # 현재 작업 디렉토리 확인

      # 전체 디렉토리 구조 출력 (디버깅용)
      - name: List directory contents
        run: ls -R  # 전체 디렉토리 구조 출력

      # Node.js 설정 - React 빌드를 위한 Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # pnpm 설치
      - name: Install pnpm
        run: npm install -g pnpm

      # .env 파일 생성 - GitHub Secrets에서 환경 변수를 가져와 .env 파일로 생성
      - name: Create .env file
        working-directory: ./fe
        run: |
          touch .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}" >> .env

      # pnpm install - 의존성 설치
      - name: Install dependencies
        run: pnpm install
        working-directory: ./fe  # 프론트엔드 프로젝트 폴더로 이동

      # pnpm run build - 프로젝트 빌드
      - name: Build project
        run: pnpm run build
        working-directory: ./fe

      # EC2 서버로 파일 배포
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./fe/build/*"  # 빌드된 파일들을 전송
          target: "/var/www/buddyguard-frontend"  # EC2 서버의 프론트엔드 파일 경로
