name: buddyGuard Frontend CI/CD using github actions & docker

# dev-fe 브랜치에 push가 되었을 때 실행
on:
  push:
    branches:
      - dev-fe  # dev-fe 브랜치에서 푸시 이벤트 발생 시 실행
  workflow_dispatch:  # 수동으로 트리거 가능하게 설정

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # 현재 작업 디렉토리 출력 (디버깅용)
      - name: Print working directory for debugging
        run: pwd  # 현재 작업 디렉토리 확인

      # 전체 디렉토리 구조 출력 (디버깅용)
      - name: List directory contents
        run: ls -R  # 전체 디렉토리 구조 출력

      # Node.js 설정 - React 빌드를 위한 Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # .env 파일 생성 - GitHub Secrets에서 환경 변수를 가져와 .env 파일로 생성
      - name: Create .env file
        working-directory: ./fe
        run: |
          touch .env
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}" >> .env

      # npm install - 의존성 설치
      - name: Install dependencies
        run: npm install
        working-directory: ./fe  # 프론트엔드 프로젝트 폴더로 이동

      # Docker 빌드 및 푸시
      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./fe/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/buddyguard-frontend:latest ./fe
          docker push ${{ secrets.DOCKER_USERNAME }}/buddyguard-frontend:latest

      # EC2 서버로 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # 기존 컨테이너 중지 및 삭제
            if [ $(sudo docker ps -q -f name=buddyguard-frontend-container) ]; then
              sudo docker stop buddyguard-frontend-container
              sudo docker rm buddyguard-frontend-container
            fi
            
            # 최신 도커 이미지 풀
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/buddyguard-frontend:latest
            
            # 새 컨테이너 실행
            sudo docker run -d --name buddyguard-frontend-container -p 8083:8082 ${{ secrets.DOCKER_USERNAME }}/buddyguard-frontend:latest
            
            # 불필요한 도커 이미지 정리
            sudo docker image prune -f
